### ISSUE TITLE
Cannot be installed using HACS on HA 2021.11

### ISSUE THREAD

**Issue by bagges** [weltenwort/home-assistant-rct-power-integration#161]
## Versions
 * Version of the custom_component: 0.8.1
 * Version of HACS: 1.17.2
 * Version of Home Assistant: 2021.11.4

## Describe the bug
I cannot find the integration within HACS. Searching for RCT Power does not return any results.

**Comment by weltenwort** [comment]
You're right, it doesn't show anymore :thinking: Thanks for the report, I'll look into it.

**Comment by weltenwort** [comment]
:information_source: This will be fixed by hacs/default#1135 , which is pending review and merge.

**Comment by weltenwort** [comment]
hacs/default#1135 has been merged. Please let me know if it still doesn't show up.
