### ISSUE TITLE
Unknown error occured when connecting Axpert MKS4

### ISSUE THREAD

**Issue by Technaur** [weltenwort/home-assistant-rct-power-integration#205]
Hi,

I am trying to add my RCT Axpert MK4 inverter. But I get this error.

<img width="577" alt="image" src="https://user-images.githubusercontent.com/28387692/165088773-61564ee3-2118-451c-a10f-fe35f3729cd4.png">

I am running Home Assistant OS on a Raspberry Pi 3B+ 64bit. My inverter is connected via Wi-Fi and that is the correct IP address.

Does anyone have any idea what I am missing?

Thanks.

**Comment by weltenwort** [comment]
Hey @Technaur,

this integration is designed to work with the PV inverters produced by the German company [RCT Power](https://www.rct-power.com). So unless your device is merely a rebranding, I doubt this integration would work for you.

**Comment by weltenwort** [comment]
Please feel free to reopen if my above assumption is incorrect.
