### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by scat703** [weltenwort/home-assistant-rct-power-integration#254]
With regards to documentation on Github I would assume to see a configuration dialog for the mandatory configuration parameters at installation time, but there is none. There is also neither any menu anywhere to do the configuration after installation nor any config file beneath /config/custom_components/rct_power. So in the end I simply can't configure the integration in any way. obviously there must be somethung wrong with my installation.

**Comment by weltenwort** [comment]
Hi @scat703, the integration should ask you for the inverter's ip address, port and name when you add the integration:

![image](https://user-images.githubusercontent.com/973741/202585296-8e181bff-16fb-4b97-8cda-291481a212a1.png)

![image](https://user-images.githubusercontent.com/973741/202585351-8f0d624d-fe39-45e8-8fa0-649e6e685d53.png)

![image](https://user-images.githubusercontent.com/973741/202585371-7cd2b146-4d77-4fbd-bd09-d9f5aa29ecd3.png)

What does it show in your case?

**Comment by scat703** [comment]
Hi!

My fault, I only added the integrations using HACS zu far, but not more. It's working now, thanks!

BR

**Comment by weltenwort** [comment]
Glad to hear that it works for you!
