### ISSUE TITLE
Link to documentation is incorrect

### ISSUE THREAD

**Issue by mqatgit** [weltenwort/home-assistant-rct-power-integration#278]
Clicking on the "Documentation" link (and also the ? symbols in pop up windows) leads here: https://github.com/weltenwort/rct-power.

But there is nothing to be found there...

![image](https://user-images.githubusercontent.com/124841299/217807722-340433b8-0f00-4439-930e-52fe7779e869.png)

Observed with current version 0.10.0.

**Comment by Noiders** [comment]
manifest.json line 3 and 4 need to be updated with correct url

  "documentation": "https://github.com/weltenwort/home-assistant-rct-power-integration",
  "issue_tracker": "https://github.com/weltenwort/home-assistant-rct-power-integration/issues",

**Comment by weltenwort** [comment]
Thank you for reporting this. The fix from #280 should be included in the next release.
