### ISSUE TITLE
Integrate into OpenHab

### ISSUE THREAD

**Issue by juli-august** [weltenwort/home-assistant-rct-power-integration#327]
Hi everybody,

is there a plan to make the integration of this code available to OpenHab.
Since one month I´m the owner of a RCT System but im struggeling with getting Data from it. Your RCT integration looks promising.

Best regards from Stuttgart, Julian

**Comment by weltenwort** [comment]
Hi @juli-august,

this is written based on the Home Assistant Python infrastructure and the amazing [python-rctclient](https://github.com/svalouch/python-rctclient/) library. Porting all this to Java for OpenHab would probably be quite a bit of work. There might be a way to use the python-rctclient library via Jython or some FFI mechanism in OpenHab, but I don't have any further expertise in either.

If you were to undertake such a project I'd be happy to share what I learned about the quirks in RCT's proprietary protocol, of course.
