### ISSUE TITLE
deprecated constants prevent the integration from loading in new Home Assistant for RPI5

### ISSUE THREAD

**Issue by kantokant** [weltenwort/home-assistant-rct-power-integration#330]
I'm using the integration (0.10.0) with my RCT solar power system, with Home Assistant on Raspberry PI 3B

@weltenwort It has been working perfectly for me for months now, tremendous piece of work, thank you very much!

We are currently beta testing the next Home Assistant release to enable the jump onto the Raspberry PI 5 platform

Currently running RPI5 HA with
Core 2024.1.0b2
Supervisor 2023.12.1
Operating System 11.3.rc1
Frontend 20231228.0

On HA startup the integration fails to load, with these warnings in the protocol:

```
POWER_VOLT_AMPERE was used from rct_power, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfApparentPower.VOLT_AMPERE instead, please create a bug report

POWER_WATT was used from rct_power, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPower.WATT instead, please create a bug report

TEMP_CELSIUS was used from rct_power, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report

TEMP_FAHRENHEIT was used from rct_power, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.FAHRENHEIT instead, please create a bug report

TEMP_KELVIN was used from rct_power, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.KELVIN instead, please create a bug report
```

Do you think that this can be adjusted, to ensure compatibility with the new HA for RPI5?

You also might want to take a look at the HA developer discussion: https://github.com/home-assistant/operating-system/discussions/2844#discussioncomment-7976705

**Comment by weltenwort** [comment]
Thanks for reporting this! I just released https://github.com/weltenwort/home-assistant-rct-power-integration/releases/tag/v0.11.0, which should remove these deprecation warnings.
